startuml
Actor JAU as C
Control GUI as GUI
Participant DataContext as DC
Participant TicketHandler as T
Database Database as D


C -> GUI: 1.1: Press login button
activate GUI
GUI -> DC: 1.2: AuthUser(username, password)
deactivate GUI
DC --> D: 1.3: Check authentication
activate D
D --> DC: 1.4: Authentication confirmed
deactivate D
activate DC
DC --> GUI: 1.5: User authenticated
deactivate DC
activate GUI
GUI --> GUI: 1.6: User instance of Customer

GUI --> T: 1.7: Create new handler
deactivate GUI
activate T
T --> C: 1.8: Ready for input
deactivate T

@enduml